apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  storageClassName: jenkins
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /jenkins-volume/